### ISSUE TITLE
Viewport camera axis

### ISSUE THREAD

**Issue by The3dVehicleguy** [Coalition-of-Freeware-Developers/Scenery-Editor-X#10]
### Feature: 
I would like the ability to view the orientation of my camera relative to my active scene 
---------------------------------------------------------------------

### Describe the feature and how it will work:

I would like to be able to work on an airport scenery and see in my active viewport a representation of the current X,Y,Z axis my camera is in relative to my scene's origin position. This would be a small UI element in the lower right hand corner of the active user 3d viewport.
---------------------------------------------------------------------
> [!CAUTION]
> Tasks are to be added to a by developers.
### Tasks:

- [ ] Implement reading of camera scene position
- [ ] Write UI element for axis indicator
- [ ] Write axis vertex shader
