### ISSUE TITLE
Write scene manager

### ISSUE THREAD

**Issue by The3dVehicleguy** [Coalition-of-Freeware-Developers/Scenery-Editor-X#11]
### Feature: 
I would like the ability to view the different objects that are added to the current scene.
---------------------------------------------------------------------

### Describe the feature and how it will work:

I would like to be able to work on an airport scenery inside a project scene. This would allow me to add multiple objects and modify the scenery in this project and allow me to open multiple different instances of Scenery Editor X without them all trying to modify the same loaded project.
---------------------------------------------------------------------
> [!CAUTION]
> Tasks are to be added to a by developers.
### Tasks:

- [ ] Implement scene definition
- [ ] Implement custom project scene buffer
- [ ] Write custom scenery project file format (This will help when associating the data needed for creation and editing)
- [ ] Implement project IO functions
- [ ] Implement IO functions to correlate to renderer
