### ISSUE TITLE
I would like the ability to view the airport at different times of the day/night cycle.

### ISSUE THREAD

**Issue by The3dVehicleguy** [Coalition-of-Freeware-Developers/Scenery-Editor-X#16]
### Feature: 
I would like the ability to view the airport at different times of the day/night cycle.
---------------------------------------------------------------------

### Describe the feature and how it will work:

I would like to be able to work on an airport scenery and modify the time of day and month to get a good visible representation of the day and night lighting of the airport and how the different models and textures will represent at all different lighting and season changes. 
---------------------------------------------------------------------
> [!CAUTION]
> Tasks are to be added to a by developers.
### Tasks:

- [ ] Implement reading of airport lat. long. coordinates to send to sun shader
- [ ] Write sun light source shader
- [ ] Write moon and night shader
- [ ] Write atmosphere coloration and light scattering based on lighting 
- [ ] Implement function to calculate time of day, and month of UTC time 
- [ ] Implement function to calculate position and degree of the sun and moon in radians relative to world origin
- [ ] Implement function to send the sun and moon position to sky and sun lighting shaders
- [ ] Implement time of day slider UI to modify the in viewport displayed time
