### ISSUE TITLE
Convert project into a CMake project

### ISSUE THREAD

**Issue by The3dVehicleguy** [Coalition-of-Freeware-Developers/Scenery-Editor-X#21]
### Feature: 
I would like the project to be generated with CMake
---------------------------------------------------------------------

### Describe the feature and how it will work:

I would like to be able to simplify the onboarding and project generation so that the project development can be standardized for all developers and more automated.
---------------------------------------------------------------------
> [!CAUTION]
> Tasks are to be added to a by developers.
### Tasks:

- [x] Create CMakeLists file for the root project.
- [x] Split up each project into its own `CMakeLists.txt`.
- [x] Convert all applicable submodules to a vcpkg CMake toolchain.
- [x] Add precompile definitions and compiler flags.
- [x] Confirm CMake Project Builds.
- [x] Create `SetupProject.bat` script to make easy to generate the project.
