### ISSUE TITLE
Create project file format

### ISSUE THREAD

**Issue by The3dVehicleguy** [Coalition-of-Freeware-Developers/Scenery-Editor-X#22]
### Feature: 
I would like a new scene project file format that is easy to read.
---------------------------------------------------------------------

### Describe the feature and how it will work:

I would like a new file format to be created to manage the project scenes inside of Scenery Editor X. I want this project format to be able to be read in any text editor with features similar to an `.ini` file and `.json` format but has more options specialized for managing expanded properties utilized with X-Plane 12 scenery. 

> [!NOTE]
> File extension for Scenery Editor X project: **`.edX`**
---------------------------------------------------------------------
> [!CAUTION]
> Tasks are to be added to a by developers.
### Tasks:

- [x] Implement definitions for format structure.
- [x] Setup file formats to be called via `.dll`.
- [x] Write file format parser.
- [x] Write file format operations.
- [x] Create file stream operations.
- [x] Create file writing functions.
- [x] Create file reading functions.
- [x] Create file extension registry association.
- [ ] Implement format operations into Scenery Editor X application.
