### ISSUE TITLE
Create project library file format

### ISSUE THREAD

**Issue by The3dVehicleguy** [Coalition-of-Freeware-Developers/Scenery-Editor-X#23]
### Feature: 
I would like a new file format to allow organization and editing of X-Plane 12 libraries.
---------------------------------------------------------------------

### Describe the feature and how it will work:

I would like a new file format to be created to manage the libraries included into the Scenery Editor X project files. The file format helps with keeping version control and items in a X-Plane library by versioning and adding extra values and strings to enable source control and custom asset addition from being created inside Scenery Editor X.

> [!NOTE]
> File extension for Scenery Editor X libraries: **`.edX.lib`**
---------------------------------------------------------------------
> [!CAUTION]
> Tasks are to be added to a by developers.
### Tasks:

- [x] Implement definitions for format structure.
- [x] Setup file formats to be called via `.dll`.
- [x] Write file format parser.
- [x] Write file format operations.
- [ ] Write file conversion from `library.txt` -> `library.edx.lib`.
- [ ] Write file conversion from `library.edx.lib`  -> `library.txt`.
- [ ] Create file stream operations.
- [x] Create file writing functions.
- [x] Create file reading functions.
- [x] Create file extension registry association.
- [ ] Implement format operations into Scenery Editor X application.
