### ISSUE TITLE
Import & Convert WED XML project files to work in Scenery Editor X

### ISSUE THREAD

**Issue by The3dVehicleguy** [Coalition-of-Freeware-Developers/Scenery-Editor-X#24]
### Feature: 
I would like to be able to convert WED XML project files into `.edX`  project files.
---------------------------------------------------------------------

### Describe the feature and how it will work:

I would like to be able to take airport projects developed in the WED program and convert them into compatible Scenery Editor X project files to be utilized inside Scenery Editor X. 

> [!NOTE]
> File extension for Scenery Editor X project: **`.edX`**
---------------------------------------------------------------------
> [!CAUTION]
> Tasks are to be added to a by developers.
### Tasks:

- [ ] Implement function to parse XML formats.
- [ ] Setup file conversion process to be called via `.dll`.
- [ ] Write xml format assert.
- [ ] Create file stream operations.
- [ ] Create file buffer.
- [ ] Write functions to convert data structures.
- [ ] Implement format operations into Scenery Editor X application.
- [ ] Write command line access script to be called for converting the file formats in "right-click" context menu. 
- [ ] Create file conversion operation script in registry.
