### ISSUE TITLE
Infinite grid plane

### ISSUE THREAD

**Issue by The3dVehicleguy** [Coalition-of-Freeware-Developers/Scenery-Editor-X#3]
### Feature: 
I would like the ability to get a orientation and scale reference in my 3d viewport
---------------------------------------------------------------------

### Describe the feature and how it will work:

I would like to be able to work on an airport scenery and view my orientation to the ground and scale of the world with a infinite spanning grid plane to represent the ground plane. This grid line spacing, color, line thickness, and visibility  can be modified to the users preference. The grid unit is in meters and one square represent a 1x1 meter space.
---------------------------------------------------------------------
> [!CAUTION]
> Tasks are to be added to a by developers.
### Tasks:

- [x] Write grid vertex shader
- [x] Write grid fragment shader
- [x] Implement view manipulation and rendering based on camera position and angle.
- [ ] Implement UI options to allow the user to modify the grid shader parameters
