### ISSUE TITLE
Normal map shader

### ISSUE THREAD

**Issue by The3dVehicleguy** [Coalition-of-Freeware-Developers/Scenery-Editor-X#5]
### Feature: 
I would like the ability to normal map textures in the 3d viewport
---------------------------------------------------------------------

### Describe the feature and how it will work:

I would like to be able to view normal map textures in the 3d viewport. I want them to display accurately as they do in X-Plane 12. This feature would help users be able to better visualize their airport/ scenery details and test custom made assets without having to load them in X-Plane 12.
---------------------------------------------------------------------
> [!CAUTION]
> Tasks are to be added to a by developers.
### Tasks:

- [ ] Write normal map fragment shader
- [ ] Implement reading of normal map texture from an individual file
- [ ] Implement reading of normal map texture from model file association
- [ ] Implement reading of return shadow position from normal map from light position in relation to camera position
